/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthDebugRouteImport } from './routes/auth-debug'
import { Route as TvRouteImport } from './routes/tv'
import { Route as ShellAcompanhamentoRouteImport } from './routes/_shell.acompanhamento'
import { Route as ShellComissoesRouteImport } from './routes/_shell.comissoes'
import { Route as ShellConfigRouteImport } from './routes/_shell.config'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellEquipeRouteImport } from './routes/_shell.equipe'
import { Route as ShellImportarRouteImport } from './routes/_shell.importar'
import { Route as ShellLogsRoboRouteImport } from './routes/_shell.logs-robo'
import { Route as ShellMeusClientesRouteImport } from './routes/_shell.meus-clientes'
import { Route as ShellNotificacoesRouteImport } from './routes/_shell.notificacoes'
import { Route as ShellOperacaoCloserRouteImport } from './routes/_shell.operacao-closer'
import { Route as ShellPipelineRouteImport } from './routes/_shell.pipeline'
import { Route as ShellRelatoriosRouteImport } from './routes/_shell.relatorios'
import { Route as ShellSuporteRouteImport } from './routes/_shell.suporte'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthNovaSenhaRouteImport } from './routes/auth.nova-senha'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as ShellClientesIndexRouteImport } from './routes/_shell.clientes.index'
import { Route as ShellClientesIdRouteImport } from './routes/_shell.clientes.$id'
import { Route as ShellImportarErrosRouteImport } from './routes/_shell.importar.erros'
import { Route as ShellImportarInicialRouteImport } from './routes/_shell.importar.inicial'
import { Route as ShellOperacaoCloserIdRouteImport } from './routes/_shell.operacao-closer.$id'
import { Route as ShellSuporteIndexRouteImport } from './routes/_shell.suporte.index'
import { Route as ShellSuporteIdRouteImport } from './routes/_shell.suporte.$id'
import { Route as ShellSuporteCentralRouteImport } from './routes/_shell.suporte.central'
import { Route as ShellVendasIdRouteImport } from './routes/_shell.vendas.$id'
import { Route as ApiPublicCronPushDispatchRouteImport } from './routes/api/public/cron/push-dispatch'
import { Route as ApiPublicCronSlaCheckRouteImport } from './routes/api/public/cron/sla-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDebugRoute = AuthDebugRouteImport.update({
  id: '/auth-debug',
  path: '/auth-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAcompanhamentoRoute = ShellAcompanhamentoRouteImport.update({
  id: '/acompanhamento',
  path: '/acompanhamento',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComissoesRoute = ShellComissoesRouteImport.update({
  id: '/comissoes',
  path: '/comissoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellConfigRoute = ShellConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellEquipeRoute = ShellEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportarRoute = ShellImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogsRoboRoute = ShellLogsRoboRouteImport.update({
  id: '/logs-robo',
  path: '/logs-robo',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeusClientesRoute = ShellMeusClientesRouteImport.update({
  id: '/meus-clientes',
  path: '/meus-clientes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificacoesRoute = ShellNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOperacaoCloserRoute = ShellOperacaoCloserRouteImport.update({
  id: '/operacao-closer',
  path: '/operacao-closer',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPipelineRoute = ShellPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRelatoriosRoute = ShellRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSuporteRoute = ShellSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => ShellRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNovaSenhaRoute = AuthNovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const ShellClientesIndexRoute = ShellClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellClientesIdRoute = ShellClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ShellImportarErrosRoute = ShellImportarErrosRouteImport.update({
  id: '/erros',
  path: '/erros',
  getParentRoute: () => ShellImportarRoute,
} as any)
const ShellImportarInicialRoute = ShellImportarInicialRouteImport.update({
  id: '/inicial',
  path: '/inicial',
  getParentRoute: () => ShellImportarRoute,
} as any)
const ShellOperacaoCloserIdRoute = ShellOperacaoCloserIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellOperacaoCloserRoute,
} as any)
const ShellSuporteIndexRoute = ShellSuporteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSuporteRoute,
} as any)
const ShellSuporteIdRoute = ShellSuporteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellSuporteRoute,
} as any)
const ShellSuporteCentralRoute = ShellSuporteCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => ShellSuporteRoute,
} as any)
const ShellVendasIdRoute = ShellVendasIdRouteImport.update({
  id: '/vendas/$id',
  path: '/vendas/$id',
  getParentRoute: () => ShellRoute,
} as any)
const ApiPublicCronPushDispatchRoute =
  ApiPublicCronPushDispatchRouteImport.update({
    id: '/api/public/cron/push-dispatch',
    path: '/api/public/cron/push-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSlaCheckRoute = ApiPublicCronSlaCheckRouteImport.update({
  id: '/api/public/cron/sla-check',
  path: '/api/public/cron/sla-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/tv': typeof TvRoute
  '/acompanhamento': typeof ShellAcompanhamentoRoute
  '/comissoes': typeof ShellComissoesRoute
  '/config': typeof ShellConfigRoute
  '/dashboard': typeof ShellDashboardRoute
  '/equipe': typeof ShellEquipeRoute
  '/importar': typeof ShellImportarRouteWithChildren
  '/logs-robo': typeof ShellLogsRoboRoute
  '/meus-clientes': typeof ShellMeusClientesRoute
  '/notificacoes': typeof ShellNotificacoesRoute
  '/operacao-closer': typeof ShellOperacaoCloserRouteWithChildren
  '/pipeline': typeof ShellPipelineRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/suporte': typeof ShellSuporteRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/': typeof AuthIndexRoute
  '/clientes/$id': typeof ShellClientesIdRoute
  '/importar/erros': typeof ShellImportarErrosRoute
  '/importar/inicial': typeof ShellImportarInicialRoute
  '/operacao-closer/$id': typeof ShellOperacaoCloserIdRoute
  '/suporte/$id': typeof ShellSuporteIdRoute
  '/suporte/central': typeof ShellSuporteCentralRoute
  '/vendas/$id': typeof ShellVendasIdRoute
  '/clientes/': typeof ShellClientesIndexRoute
  '/suporte/': typeof ShellSuporteIndexRoute
  '/api/public/cron/push-dispatch': typeof ApiPublicCronPushDispatchRoute
  '/api/public/cron/sla-check': typeof ApiPublicCronSlaCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-debug': typeof AuthDebugRoute
  '/tv': typeof TvRoute
  '/acompanhamento': typeof ShellAcompanhamentoRoute
  '/comissoes': typeof ShellComissoesRoute
  '/config': typeof ShellConfigRoute
  '/dashboard': typeof ShellDashboardRoute
  '/equipe': typeof ShellEquipeRoute
  '/importar': typeof ShellImportarRouteWithChildren
  '/logs-robo': typeof ShellLogsRoboRoute
  '/meus-clientes': typeof ShellMeusClientesRoute
  '/notificacoes': typeof ShellNotificacoesRoute
  '/operacao-closer': typeof ShellOperacaoCloserRouteWithChildren
  '/pipeline': typeof ShellPipelineRoute
  '/relatorios': typeof ShellRelatoriosRoute
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth': typeof AuthIndexRoute
  '/clientes/$id': typeof ShellClientesIdRoute
  '/importar/erros': typeof ShellImportarErrosRoute
  '/importar/inicial': typeof ShellImportarInicialRoute
  '/operacao-closer/$id': typeof ShellOperacaoCloserIdRoute
  '/suporte/$id': typeof ShellSuporteIdRoute
  '/suporte/central': typeof ShellSuporteCentralRoute
  '/vendas/$id': typeof ShellVendasIdRoute
  '/clientes': typeof ShellClientesIndexRoute
  '/suporte': typeof ShellSuporteIndexRoute
  '/api/public/cron/push-dispatch': typeof ApiPublicCronPushDispatchRoute
  '/api/public/cron/sla-check': typeof ApiPublicCronSlaCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth-debug': typeof AuthDebugRoute
  '/tv': typeof TvRoute
  '/_shell/acompanhamento': typeof ShellAcompanhamentoRoute
  '/_shell/comissoes': typeof ShellComissoesRoute
  '/_shell/config': typeof ShellConfigRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/equipe': typeof ShellEquipeRoute
  '/_shell/importar': typeof ShellImportarRouteWithChildren
  '/_shell/logs-robo': typeof ShellLogsRoboRoute
  '/_shell/meus-clientes': typeof ShellMeusClientesRoute
  '/_shell/notificacoes': typeof ShellNotificacoesRoute
  '/_shell/operacao-closer': typeof ShellOperacaoCloserRouteWithChildren
  '/_shell/pipeline': typeof ShellPipelineRoute
  '/_shell/relatorios': typeof ShellRelatoriosRoute
  '/_shell/suporte': typeof ShellSuporteRouteWithChildren
  '/auth/nova-senha': typeof AuthNovaSenhaRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/': typeof AuthIndexRoute
  '/_shell/clientes/$id': typeof ShellClientesIdRoute
  '/_shell/importar/erros': typeof ShellImportarErrosRoute
  '/_shell/importar/inicial': typeof ShellImportarInicialRoute
  '/_shell/operacao-closer/$id': typeof ShellOperacaoCloserIdRoute
  '/_shell/suporte/$id': typeof ShellSuporteIdRoute
  '/_shell/suporte/central': typeof ShellSuporteCentralRoute
  '/_shell/vendas/$id': typeof ShellVendasIdRoute
  '/_shell/clientes/': typeof ShellClientesIndexRoute
  '/_shell/suporte/': typeof ShellSuporteIndexRoute
  '/api/public/cron/push-dispatch': typeof ApiPublicCronPushDispatchRoute
  '/api/public/cron/sla-check': typeof ApiPublicCronSlaCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-debug'
    | '/tv'
    | '/acompanhamento'
    | '/comissoes'
    | '/config'
    | '/dashboard'
    | '/equipe'
    | '/importar'
    | '/logs-robo'
    | '/meus-clientes'
    | '/notificacoes'
    | '/operacao-closer'
    | '/pipeline'
    | '/relatorios'
    | '/suporte'
    | '/auth/nova-senha'
    | '/auth/reset'
    | '/auth/'
    | '/clientes/$id'
    | '/importar/erros'
    | '/importar/inicial'
    | '/operacao-closer/$id'
    | '/suporte/$id'
    | '/suporte/central'
    | '/vendas/$id'
    | '/clientes/'
    | '/suporte/'
    | '/api/public/cron/push-dispatch'
    | '/api/public/cron/sla-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-debug'
    | '/tv'
    | '/acompanhamento'
    | '/comissoes'
    | '/config'
    | '/dashboard'
    | '/equipe'
    | '/importar'
    | '/logs-robo'
    | '/meus-clientes'
    | '/notificacoes'
    | '/operacao-closer'
    | '/pipeline'
    | '/relatorios'
    | '/auth/nova-senha'
    | '/auth/reset'
    | '/auth'
    | '/clientes/$id'
    | '/importar/erros'
    | '/importar/inicial'
    | '/operacao-closer/$id'
    | '/suporte/$id'
    | '/suporte/central'
    | '/vendas/$id'
    | '/clientes'
    | '/suporte'
    | '/api/public/cron/push-dispatch'
    | '/api/public/cron/sla-check'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/auth'
    | '/auth-debug'
    | '/tv'
    | '/_shell/acompanhamento'
    | '/_shell/comissoes'
    | '/_shell/config'
    | '/_shell/dashboard'
    | '/_shell/equipe'
    | '/_shell/importar'
    | '/_shell/logs-robo'
    | '/_shell/meus-clientes'
    | '/_shell/notificacoes'
    | '/_shell/operacao-closer'
    | '/_shell/pipeline'
    | '/_shell/relatorios'
    | '/_shell/suporte'
    | '/auth/nova-senha'
    | '/auth/reset'
    | '/auth/'
    | '/_shell/clientes/$id'
    | '/_shell/importar/erros'
    | '/_shell/importar/inicial'
    | '/_shell/operacao-closer/$id'
    | '/_shell/suporte/$id'
    | '/_shell/suporte/central'
    | '/_shell/vendas/$id'
    | '/_shell/clientes/'
    | '/_shell/suporte/'
    | '/api/public/cron/push-dispatch'
    | '/api/public/cron/sla-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthDebugRoute: typeof AuthDebugRoute
  TvRoute: typeof TvRoute
  ApiPublicCronPushDispatchRoute: typeof ApiPublicCronPushDispatchRoute
  ApiPublicCronSlaCheckRoute: typeof ApiPublicCronSlaCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-debug': {
      id: '/auth-debug'
      path: '/auth-debug'
      fullPath: '/auth-debug'
      preLoaderRoute: typeof AuthDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/acompanhamento': {
      id: '/_shell/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/acompanhamento'
      preLoaderRoute: typeof ShellAcompanhamentoRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comissoes': {
      id: '/_shell/comissoes'
      path: '/comissoes'
      fullPath: '/comissoes'
      preLoaderRoute: typeof ShellComissoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/config': {
      id: '/_shell/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ShellConfigRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/equipe': {
      id: '/_shell/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof ShellEquipeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/importar': {
      id: '/_shell/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ShellImportarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/logs-robo': {
      id: '/_shell/logs-robo'
      path: '/logs-robo'
      fullPath: '/logs-robo'
      preLoaderRoute: typeof ShellLogsRoboRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meus-clientes': {
      id: '/_shell/meus-clientes'
      path: '/meus-clientes'
      fullPath: '/meus-clientes'
      preLoaderRoute: typeof ShellMeusClientesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notificacoes': {
      id: '/_shell/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof ShellNotificacoesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/operacao-closer': {
      id: '/_shell/operacao-closer'
      path: '/operacao-closer'
      fullPath: '/operacao-closer'
      preLoaderRoute: typeof ShellOperacaoCloserRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pipeline': {
      id: '/_shell/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof ShellPipelineRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/relatorios': {
      id: '/_shell/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof ShellRelatoriosRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/suporte': {
      id: '/_shell/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof ShellSuporteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/nova-senha': {
      id: '/auth/nova-senha'
      path: '/nova-senha'
      fullPath: '/auth/nova-senha'
      preLoaderRoute: typeof AuthNovaSenhaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_shell/clientes/': {
      id: '/_shell/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ShellClientesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/clientes/$id': {
      id: '/_shell/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ShellClientesIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/importar/erros': {
      id: '/_shell/importar/erros'
      path: '/erros'
      fullPath: '/importar/erros'
      preLoaderRoute: typeof ShellImportarErrosRouteImport
      parentRoute: typeof ShellImportarRoute
    }
    '/_shell/importar/inicial': {
      id: '/_shell/importar/inicial'
      path: '/inicial'
      fullPath: '/importar/inicial'
      preLoaderRoute: typeof ShellImportarInicialRouteImport
      parentRoute: typeof ShellImportarRoute
    }
    '/_shell/operacao-closer/$id': {
      id: '/_shell/operacao-closer/$id'
      path: '/$id'
      fullPath: '/operacao-closer/$id'
      preLoaderRoute: typeof ShellOperacaoCloserIdRouteImport
      parentRoute: typeof ShellOperacaoCloserRoute
    }
    '/_shell/suporte/': {
      id: '/_shell/suporte/'
      path: '/'
      fullPath: '/suporte/'
      preLoaderRoute: typeof ShellSuporteIndexRouteImport
      parentRoute: typeof ShellSuporteRoute
    }
    '/_shell/suporte/$id': {
      id: '/_shell/suporte/$id'
      path: '/$id'
      fullPath: '/suporte/$id'
      preLoaderRoute: typeof ShellSuporteIdRouteImport
      parentRoute: typeof ShellSuporteRoute
    }
    '/_shell/suporte/central': {
      id: '/_shell/suporte/central'
      path: '/central'
      fullPath: '/suporte/central'
      preLoaderRoute: typeof ShellSuporteCentralRouteImport
      parentRoute: typeof ShellSuporteRoute
    }
    '/_shell/vendas/$id': {
      id: '/_shell/vendas/$id'
      path: '/vendas/$id'
      fullPath: '/vendas/$id'
      preLoaderRoute: typeof ShellVendasIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/public/cron/push-dispatch': {
      id: '/api/public/cron/push-dispatch'
      path: '/api/public/cron/push-dispatch'
      fullPath: '/api/public/cron/push-dispatch'
      preLoaderRoute: typeof ApiPublicCronPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sla-check': {
      id: '/api/public/cron/sla-check'
      path: '/api/public/cron/sla-check'
      fullPath: '/api/public/cron/sla-check'
      preLoaderRoute: typeof ApiPublicCronSlaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellImportarRouteChildren {
  ShellImportarErrosRoute: typeof ShellImportarErrosRoute
  ShellImportarInicialRoute: typeof ShellImportarInicialRoute
}

const ShellImportarRouteChildren: ShellImportarRouteChildren = {
  ShellImportarErrosRoute: ShellImportarErrosRoute,
  ShellImportarInicialRoute: ShellImportarInicialRoute,
}

const ShellImportarRouteWithChildren = ShellImportarRoute._addFileChildren(
  ShellImportarRouteChildren,
)

interface ShellOperacaoCloserRouteChildren {
  ShellOperacaoCloserIdRoute: typeof ShellOperacaoCloserIdRoute
}

const ShellOperacaoCloserRouteChildren: ShellOperacaoCloserRouteChildren = {
  ShellOperacaoCloserIdRoute: ShellOperacaoCloserIdRoute,
}

const ShellOperacaoCloserRouteWithChildren =
  ShellOperacaoCloserRoute._addFileChildren(ShellOperacaoCloserRouteChildren)

interface ShellSuporteRouteChildren {
  ShellSuporteIdRoute: typeof ShellSuporteIdRoute
  ShellSuporteCentralRoute: typeof ShellSuporteCentralRoute
  ShellSuporteIndexRoute: typeof ShellSuporteIndexRoute
}

const ShellSuporteRouteChildren: ShellSuporteRouteChildren = {
  ShellSuporteIdRoute: ShellSuporteIdRoute,
  ShellSuporteCentralRoute: ShellSuporteCentralRoute,
  ShellSuporteIndexRoute: ShellSuporteIndexRoute,
}

const ShellSuporteRouteWithChildren = ShellSuporteRoute._addFileChildren(
  ShellSuporteRouteChildren,
)

interface ShellRouteChildren {
  ShellAcompanhamentoRoute: typeof ShellAcompanhamentoRoute
  ShellComissoesRoute: typeof ShellComissoesRoute
  ShellConfigRoute: typeof ShellConfigRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellEquipeRoute: typeof ShellEquipeRoute
  ShellImportarRoute: typeof ShellImportarRouteWithChildren
  ShellLogsRoboRoute: typeof ShellLogsRoboRoute
  ShellMeusClientesRoute: typeof ShellMeusClientesRoute
  ShellNotificacoesRoute: typeof ShellNotificacoesRoute
  ShellOperacaoCloserRoute: typeof ShellOperacaoCloserRouteWithChildren
  ShellPipelineRoute: typeof ShellPipelineRoute
  ShellRelatoriosRoute: typeof ShellRelatoriosRoute
  ShellSuporteRoute: typeof ShellSuporteRouteWithChildren
  ShellClientesIdRoute: typeof ShellClientesIdRoute
  ShellVendasIdRoute: typeof ShellVendasIdRoute
  ShellClientesIndexRoute: typeof ShellClientesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAcompanhamentoRoute: ShellAcompanhamentoRoute,
  ShellComissoesRoute: ShellComissoesRoute,
  ShellConfigRoute: ShellConfigRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellEquipeRoute: ShellEquipeRoute,
  ShellImportarRoute: ShellImportarRouteWithChildren,
  ShellLogsRoboRoute: ShellLogsRoboRoute,
  ShellMeusClientesRoute: ShellMeusClientesRoute,
  ShellNotificacoesRoute: ShellNotificacoesRoute,
  ShellOperacaoCloserRoute: ShellOperacaoCloserRouteWithChildren,
  ShellPipelineRoute: ShellPipelineRoute,
  ShellRelatoriosRoute: ShellRelatoriosRoute,
  ShellSuporteRoute: ShellSuporteRouteWithChildren,
  ShellClientesIdRoute: ShellClientesIdRoute,
  ShellVendasIdRoute: ShellVendasIdRoute,
  ShellClientesIndexRoute: ShellClientesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AuthRouteChildren {
  AuthNovaSenhaRoute: typeof AuthNovaSenhaRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthNovaSenhaRoute: AuthNovaSenhaRoute,
  AuthResetRoute: AuthResetRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthDebugRoute: AuthDebugRoute,
  TvRoute: TvRoute,
  ApiPublicCronPushDispatchRoute: ApiPublicCronPushDispatchRoute,
  ApiPublicCronSlaCheckRoute: ApiPublicCronSlaCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
